// Code generated by encore. DO NOT EDIT.

package auth

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Register creates a new user account via the configured auth provider.
func Register(ctx context.Context, p *RegisterRequest) (*TokenResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*TokenResponse)(nil), nil
}

// Login authenticates an existing user via the configured auth provider.
func Login(ctx context.Context, p *LoginRequest) (*TokenResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*TokenResponse)(nil), nil
}

// Refresh exchanges a refresh token for a new access token.
func Refresh(ctx context.Context, p *RefreshRequest) (*TokenResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*TokenResponse)(nil), nil
}

// Logout revokes the current session.
func Logout(ctx context.Context, p *LogoutRequest) (*MessageResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*MessageResponse)(nil), nil
}

// ForgotPassword triggers a password reset email.
func ForgotPassword(ctx context.Context, p *ForgotPasswordRequest) (*MessageResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*MessageResponse)(nil), nil
}

// ResetPassword completes a password reset.
func ResetPassword(ctx context.Context, p *ResetPasswordRequest) (*MessageResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*MessageResponse)(nil), nil
}

// EnrollMFA begins TOTP MFA enrollment.
func EnrollMFA(ctx context.Context) (*MFAEnrollmentResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*MFAEnrollmentResponse)(nil), nil
}

// VerifyMFA confirms MFA enrollment with a TOTP code.
func VerifyMFA(ctx context.Context, p *MFACodeRequest) (*MessageResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*MessageResponse)(nil), nil
}

// RemoveMFA removes MFA from the account.
func RemoveMFA(ctx context.Context) (*MessageResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*MessageResponse)(nil), nil
}

// CreateTestUser creates a pre-confirmed user via Supabase Admin API.
// Dev/local only — bypasses email confirmation for testing.
func CreateTestUser(ctx context.Context, p *CreateTestUserRequest) (*CreateTestUserResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*CreateTestUserResponse)(nil), nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// Register creates a new user account via the configured auth provider.
	Register(ctx context.Context, p *RegisterRequest) (*TokenResponse, error)

	// Login authenticates an existing user via the configured auth provider.
	Login(ctx context.Context, p *LoginRequest) (*TokenResponse, error)

	// Refresh exchanges a refresh token for a new access token.
	Refresh(ctx context.Context, p *RefreshRequest) (*TokenResponse, error)

	// Logout revokes the current session.
	Logout(ctx context.Context, p *LogoutRequest) (*MessageResponse, error)

	// ForgotPassword triggers a password reset email.
	ForgotPassword(ctx context.Context, p *ForgotPasswordRequest) (*MessageResponse, error)

	// ResetPassword completes a password reset.
	ResetPassword(ctx context.Context, p *ResetPasswordRequest) (*MessageResponse, error)

	// EnrollMFA begins TOTP MFA enrollment.
	EnrollMFA(ctx context.Context) (*MFAEnrollmentResponse, error)

	// VerifyMFA confirms MFA enrollment with a TOTP code.
	VerifyMFA(ctx context.Context, p *MFACodeRequest) (*MessageResponse, error)

	// RemoveMFA removes MFA from the account.
	RemoveMFA(ctx context.Context) (*MessageResponse, error)

	// CreateTestUser creates a pre-confirmed user via Supabase Admin API.
	// Dev/local only — bypasses email confirmation for testing.
	CreateTestUser(ctx context.Context, p *CreateTestUserRequest) (*CreateTestUserResponse, error)
}
