// Code generated by encore. DO NOT EDIT.

package vital

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// CheckTables lists which required tables exist in the database.
func CheckTables(ctx context.Context) (*CheckTablesResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*CheckTablesResponse)(nil), nil
}

// RunMigration creates any missing tables using idempotent DDL.
func RunMigration(ctx context.Context) (*MigrateResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*MigrateResponse)(nil), nil
}

// Health is a public health check endpoint.
func Health(ctx context.Context) (*HealthResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*HealthResponse)(nil), nil
}

// Me returns the current authenticated user's information.
func Me(ctx context.Context) (*MeResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*MeResponse)(nil), nil
}

// RecordVital records a new vital sign reading.
func RecordVital(ctx context.Context, p *RecordVitalRequest) (*VitalReadingResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*VitalReadingResponse)(nil), nil
}

// GetVital returns a specific vital reading.
func GetVital(ctx context.Context, id string) (*VitalReadingResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*VitalReadingResponse)(nil), nil
}

// ListVitals lists vital readings with filters and pagination.
func ListVitals(ctx context.Context, p *ListVitalsRequest) (*ListVitalsResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*ListVitalsResponse)(nil), nil
}

// DeleteVital deletes a vital reading.
func DeleteVital(ctx context.Context, id string) error {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil
}

// GetSummary returns aggregated vital stats for a time range.
func GetSummary(ctx context.Context, p *SummaryRequest) (*SummaryResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*SummaryResponse)(nil), nil
}

// GetLatestVitals returns the most recent reading per vital type.
func GetLatestVitals(ctx context.Context) (*LatestVitalsResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*LatestVitalsResponse)(nil), nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// CheckTables lists which required tables exist in the database.
	CheckTables(ctx context.Context) (*CheckTablesResponse, error)

	// RunMigration creates any missing tables using idempotent DDL.
	RunMigration(ctx context.Context) (*MigrateResponse, error)

	// Health is a public health check endpoint.
	Health(ctx context.Context) (*HealthResponse, error)

	// Me returns the current authenticated user's information.
	Me(ctx context.Context) (*MeResponse, error)

	// RecordVital records a new vital sign reading.
	RecordVital(ctx context.Context, p *RecordVitalRequest) (*VitalReadingResponse, error)

	// GetVital returns a specific vital reading.
	GetVital(ctx context.Context, id string) (*VitalReadingResponse, error)

	// ListVitals lists vital readings with filters and pagination.
	ListVitals(ctx context.Context, p *ListVitalsRequest) (*ListVitalsResponse, error)

	// DeleteVital deletes a vital reading.
	DeleteVital(ctx context.Context, id string) error

	// GetSummary returns aggregated vital stats for a time range.
	GetSummary(ctx context.Context, p *SummaryRequest) (*SummaryResponse, error)

	// GetLatestVitals returns the most recent reading per vital type.
	GetLatestVitals(ctx context.Context) (*LatestVitalsResponse, error)
}
