// Code generated by encore. DO NOT EDIT.

package alert

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// ListAlerts returns a filtered, paginated list of alerts.
func ListAlerts(ctx context.Context, p *ListAlertsRequest) (*ListAlertsResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*ListAlertsResponse)(nil), nil
}

// GetAlert returns a specific alert.
func GetAlert(ctx context.Context, id string) (*AlertResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*AlertResponse)(nil), nil
}

// AcknowledgeAlert marks an alert as acknowledged.
func AcknowledgeAlert(ctx context.Context, id string) (*AlertResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*AlertResponse)(nil), nil
}

// ListThresholds returns the current user's alert thresholds.
func ListThresholds(ctx context.Context) (*ThresholdListResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*ThresholdListResponse)(nil), nil
}

// SetThreshold sets or updates a threshold for a vital type.
func SetThreshold(ctx context.Context, vitalType string, p *SetThresholdRequest) (*ThresholdResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*ThresholdResponse)(nil), nil
}

// DeleteThreshold removes a threshold (reverts to defaults).
func DeleteThreshold(ctx context.Context, vitalType string) error {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// ListAlerts returns a filtered, paginated list of alerts.
	ListAlerts(ctx context.Context, p *ListAlertsRequest) (*ListAlertsResponse, error)

	// GetAlert returns a specific alert.
	GetAlert(ctx context.Context, id string) (*AlertResponse, error)

	// AcknowledgeAlert marks an alert as acknowledged.
	AcknowledgeAlert(ctx context.Context, id string) (*AlertResponse, error)

	// ListThresholds returns the current user's alert thresholds.
	ListThresholds(ctx context.Context) (*ThresholdListResponse, error)

	// SetThreshold sets or updates a threshold for a vital type.
	SetThreshold(ctx context.Context, vitalType string, p *SetThresholdRequest) (*ThresholdResponse, error)

	// DeleteThreshold removes a threshold (reverts to defaults).
	DeleteThreshold(ctx context.Context, vitalType string) error
}
