// Code generated by encore. DO NOT EDIT.

package user

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// GetProfile returns the current user's profile.
// Auto-provisions a local profile from JWT claims on first access.
func GetProfile(ctx context.Context) (*UserProfileResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*UserProfileResponse)(nil), nil
}

// UpdateProfile updates the current user's profile fields.
func UpdateProfile(ctx context.Context, p *UpdateProfileRequest) (*UserProfileResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*UserProfileResponse)(nil), nil
}

// DeleteAccount deletes the current user's account and all associated data.
func DeleteAccount(ctx context.Context) error {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil
}

// ListDevices returns the current user's registered devices.
func ListDevices(ctx context.Context) (*DeviceListResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*DeviceListResponse)(nil), nil
}

// RegisterDevice registers a new monitoring device.
func RegisterDevice(ctx context.Context, p *RegisterDeviceRequest) (*DeviceResponse, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*DeviceResponse)(nil), nil
}

// RemoveDevice removes a registered device.
func RemoveDevice(ctx context.Context, id string) error {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// GetProfile returns the current user's profile.
	// Auto-provisions a local profile from JWT claims on first access.
	GetProfile(ctx context.Context) (*UserProfileResponse, error)

	// UpdateProfile updates the current user's profile fields.
	UpdateProfile(ctx context.Context, p *UpdateProfileRequest) (*UserProfileResponse, error)

	// DeleteAccount deletes the current user's account and all associated data.
	DeleteAccount(ctx context.Context) error

	// ListDevices returns the current user's registered devices.
	ListDevices(ctx context.Context) (*DeviceListResponse, error)

	// RegisterDevice registers a new monitoring device.
	RegisterDevice(ctx context.Context, p *RegisterDeviceRequest) (*DeviceResponse, error)

	// RemoveDevice removes a registered device.
	RemoveDevice(ctx context.Context, id string) error
}
